[metadata]
name = gptide
version = 0.3.0
description = "Gaussian Process regression tools for oceanography and engineering."
long_description = file: README.md
long_description_content_type = text/markdown
requires-python = ">=3.8"
project_urls =
    Homepage = https://github.com/TIDE-ITRH/gptide
    Bug Tracker = https://github.com/TIDE-ITRH/gptide/issues
    Changelog = https://github.com/TIDE-ITRH/gptide/releases
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Intended Audience :: Developers

[project]
name = "gptide"
version = "0.3.0"
authors = [
    { name="Lachlan Astfalck", email="lachlan.astfalck@uwa.edu.au"},
    { name="Matt Rayson", email="Matt.Rayson@uwa.edu.au" }]

[options]
package_dir =
    = src
packages = find:
install_requires =
    numpy
    scipy
    xarray
    matplotlib
    emcee

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    gptide = gptide.app:entry_point